test/run-tests
This allows to manually review PRs from others and only test the changes
that were reviewed.
=> Allow to specify commit to test for manual tests

test/run-tests
This allows to specify other settings such as TEST_DEBUG to the
inventory script.
=> Update environment instead of overwriting it

README.md, test/run-tests
It also contains two other minor corrections
=> Add more commands to be able to re-trigger tests

test/run-tests
This should kill PODs automatically if they cannot work because of missing disk space and make OpenShift spin up another one.
=> Abort if there is not enough disk space

test/run-tests
`standard-inventory-qcow2` searches for FMF in the current working directory. Run `ansible-playbook` in the directory with tests so FMF is picked up.
=> FMF support

test/run-tests
I'd like to receive some comments regarding name config, especially how it will be written in config.json (now it is top level key "test_harness_name")
=> Patches from staging branch

README.md, test/run-tests
Use standard python `logging` module for logging.
Add ability to use INFO, DEBUG, etc. levels.
=> Extend logging capabilities; use logging module

README.md, ansible/openshift-playbook.yml, ansible/tasks/pre-flight-checks.yml, openshift-objects-staging.yml
(cherry picked from commit 9b04a14688d94b6525d276d58be4f7f5eac0c8bc)
=> changes to enforce staging/prod workflow

README.md, ansible/openshift-playbook.yml, ansible/tasks/pre-flight-checks.yml
Needed to update README.md
Needed to protect against undefined use of
`test_harness_use_staging` and `test_harness_use_production`
=> more fixes for the new deployment workflow

.travis.yml, README.md, ansible/tasks/pre-flight-checks.yml, openshift-objects-staging.yml, openshift-objects.yml, tox.ini
Also upgrades ci to use py37 and ubuntu bionic
=> use master branch for staging; use production branch for production

Dockerfile
=> Dockerfile: Update from Fedora 31 to Fedora 32

ansible/tasks/fixup-dc.yml, openshift-objects-staging.yml, openshift-objects.yml
spec.selector.name must match labels.name
convert node_selector to a json string
fix securityContext setting
=> Ansible and OpenShift fixes

Dockerfile.centos7
Update Ansible version from 2.7 to 2.8
=> Dockerfile.centos7: Update Ansible version to 2.8

ansible/tasks/create-configmap.yml, ansible/tasks/create-secrets.yml
put the tempfile use inside a block so that we can use always
to ensure the tempfile is removed
=> use block/always to ensure tempfile removal

Dockerfile, Dockerfile.centos7
Signed-off-by: Wen Liang <liangwen12year@gmail.com>
=> Install rsync on the local system

test/run-tests
=> runtest: Fix "No module named 'lsr_role2collection" error

Dockerfile
Details are found in this comment.
https://github.com/linux-system-roles/test-harness/issues/115#issuecomment-723287239
=> Adding the python3-ruamel-yaml package to Dockerfile.

Dockerfile, Dockerfile.centos7, ansible/openshift-playbook.yml
docker.io recently changed their free tier download rates. Find an alternative provider.
https://www.docker.com/increase-rate-limits
=> Do not pull images from Docker.io 

test/run-tests
=> run-tests: Citool: Skip images that doesn't have openstack_image

Dockerfile.a212, test/run-tests
add subrole prefix when converting to collection
add debugging for github http traffic
=> subrole prefix with collection; debug http

test/run-tests
- add support for TEST_HARNESS_POST_SNAP_SLEEP_TIME
- add runqemu debugging
- support runqemu_args in image config
=> post snap sleep time

test/run-tests
- handle missing batch report, unknown http errors
- handle secondary rate limit
=> handle missing batch report http errors
