- test/run-tests
This avoids false-positives if for some reason the playbooks are renamed
to invalid names. Otherwise missing playbooks are reported as success
even when no tests ran.
> Report failure when no test playbooks are found

- README.md
- test/run-tests
This generalizes the images[i].setup command in config.json.
The playbook shall be given as a JSON array under the images[i].setup_plays key in config.json. This is possible because Ansible playbooks are YAML and can be represented as JSON.
Eventually, images[i].setup can be removed.
> Allow to specify arbitrary Ansible playbook in config.json.

- test/run-tests
- Use a comment like ci-check-commit:<commit hash> to whitelist a commit
- This addresses #23
> Allow to whitelist commits in PR to run CI

- Dockerfile
The way docker caches images, it is recommended to remove the package
cache to ensure that later steps do not use outdated cache files and to
reduce the image size. To avoid re-downloads of the cache, run all
commands at once.
> Run dnf commands together and remove cache

- README.md
- test/run-tests
Requiring whitlelisting of test results' uploads allows to introduce images for which no logs are uploaded. The simple HTML allows to easier access other log files.
> Allow to whitelist uploading and create simple HTML to check logs

- test/run-tests
In particular, unclaim claimed tasks and allow Python to clean up.
This should remove the need to issue `[citest pending]` when `run-tests` is terminated in the middle of task.
> Handle SIGTERM gracefully

- test/run-tests
* use date from header instead of local time when calculating sleep time
* if calculated timeout is too small (or even negative), use transient_error_wait_time
> Be more defensive when calculating timeout

- Dockerfile
References: https://github.com/Yelp/dumb-init
FYI: I did not test it locally, yet.
> Container: Use dumb-init to avoid zombie processes

- test/run-tests
To distinguish multiple instances running on the same host, add a
timestamp to the description.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/test-harness/53)
> Add timestamp to Github description

- test/run-tests
CacheControl works as an adapter inheriting from HTTPAdapter.
Use it as an adapter.
> Fix use of CacheControl

- test/run-tests
To limit the requests to the GitHub API, shuffle the images/repos once
and then handle the first possible task. So avoids making requests to
find all possible tasks to only choose one of them at the end.
> Shuffle list of images/repos once

- test/run-tests
When handling HTTPErrors, if no other action is taken, try to
print message which is usually present in responses from GitHub.
Related: https://github.com/linux-system-roles/test-harness/issues/55
> Print message from GitHub in HTTPError handling

- test/run-tests
Amend printing 'waiting' message so current state (testing/waiting) can be deduced from log.
> Fix printing of 'waiting' message

- test/run-tests
Currently used API endpoint returns paginated list of all statuses
so old entries may be pushed to second page and further. This may
lead to unnecessary retests when test-harness thinks that test result
is absent.
There is an API endpoint which returns most recent status for each
context. Use this one as we want newest statuses only anyway.
> Fix getting statuses

- Dockerfile
To avoid name squatting attacks/problems it is necessary to specify the
container registry when specifying a container image. Otherwise an image
with the same name from a different registry could be obtained.
References: https://raesene.github.io/blog/2019/09/25/typosquatting-in-a-multi-registry-world/
> Container: Specify registry for container image

- README.md
- add-staging-tag
- ansible/openshift-playbook.yml
- ansible/tasks/create-configmap.yml
- ansible/tasks/create-secrets.yml
- ansible/tasks/fixup-dc.yml
- ansible/tasks/setup-ci-environ.yml
- openshift-objects-staging.yml
- openshift-objects.yml
Added a playbook for deploying the CI environment to an
OpenShift cluster.
```
$ ansible-playbook -e test_harness_secrets_dir=$SECRETS_PATH \
-e test_harness_config_dir=$CONFIG_PATH \
-e test_harness_scc=$SCC_NAME \
ansible/openshift-playbook.yml
```
Parameters:
* `test_harness_secrets_dir` - Required - See `SECRETS_PATH`
* `test_harness_config_dir` - Required - See `CONFIG_PATH`
* `test_harness_scc` - Required - See `SCC_NAME`
* `test_harness_namespace` - Default `lsr-test-harness`
* `test_harness_sa` - Default `system:serviceaccount:{{ test_harness_namespace }
}:tester`
* `test_harness_need_node_selector` - Default `true`
* `test_harness_run_as_root` - Default `true`
* `test_harness_node_selector` - Default `{"system-roles-ci": "true"}`
* `test_harness_use_staging` - Default `true`
* …
> Use Ansible for deployment; use BuildConfig for building

- ansible/openshift-playbook.yml
configmap names are config and config-staging, not
linux-system-roles and linux-system-roles-staging
> fix configmap names

- openshift-objects.yml
set number of replicas for production to `8`.  This is how many
pods will run in production.
> use 8 pods in production

- README.md
- ansible/openshift-playbook.yml
- ansible/tasks/pre-flight-checks.yml
- openshift-objects-staging.yml
The README.md has added a section about `Deployment Workflow`
which clarifies that changes are made to `staging` first, then
to `production`, and describes the detailed steps to take to
achieve that workflow.
This also changes the ansible playbooks used to deploy to
enforce this workflow.
> changes to enforce staging/prod workflow

- ansible/openshift-playbook.yml
- ansible/tasks/pre-flight-checks-general.yml
- ansible/tasks/pre-flight-checks-openshift.yml
The PR splits pre-flight-checks to two files: one for general usage and the second one for openshift specifically.  
It will be needed for creating openstack deploy playbook
> pre-flight-checks: split checks to two files

- Dockerfile.centos7
- README.md
- ansible/openshift-playbook.yml
- openshift-objects-staging.yml
- openshift-objects.yml
- test/run-tests
This adds a container/pod for running tests using ansible 2.7 and
python 2 on centos7 as a controller node, in addition to the current
one which uses ansible 2.9/python3/Fedora 32.
The container is run in a new pod/deployment called
linux-system-roles-centos7 (and -staging).  This runs alongside
the current one.  The new one uses the same configuration as
the old one.
The status in the PR now adds the ansible version like this:
linux-system-roles-test/centos-7/ansible-2.7
or
linux-system-roles-test/fedora-31/ansible-2.9
This will be used for *all* statuses going forward.  That is,
there will be no more `linux-system-roles-test/fedora-31` - all
statuses, even for the current ansible, will include the ansible
version string.
The `run-tests` script running in the pod can now be controlled
by …
> Add support for using ansible 2.7/python 2/centos7 as controller

- Dockerfile.centos7
The RHEL rhel-system-roles packages have dependencies on jmespath.
The Fedora ansible package requires jmespath, but not the CentOS
ansible package.  We need to install jmespath on the CentOS test
controller.
> add python2-jmespath to make json_query work

- test/run-tests
The `get_statuses` method now supports paging.  It will return all
statuses from all pages in a single return value.
> paged searches for statuses

- test/run-tests
The simplistic method of paging through statuses by doing a
`get` until no more results were returned is causing us to
exceed the ratelimit.  Instead, use a larger page size, by
default 60 (which seems to work experimentally), to tide us
over until we can use a real api with real paging and real
ratelimit handling.
This adds support for a new command line parameter --max-num-statuses
and a corresponding env. var. to allow us to fine-tune the page
size.
> use larger page size instead of paging for statuses

- ansible/openshift-playbook.yml
- ansible/tasks/pre-flight-checks-general.yml
test_harness_secrets_dir and test_harness_config_dir should be set
via the playbook vars, not via set_fact in the flight check tasks.
> config and secrets dirs should be playbook vars

- openshift-objects.yml
The buildconfig must output to the "staging" imagestream tag if
not being used in production.
> buildconfig must output to staging tag if not production

- test/run-tests
Seeing error messages like this in production:
```
ERROR: Total number of statuses 61 exceeds max_num_statuses 60 statuses for xxx - please increase max_num_statuses
```
I have temporarily fixed production by using the env var setting, but
this will be wiped out at the next redeploy.
> increase num of statuses to 99 - 60 is too small

- test/run-tests
hide the citool output - redirect it to private_artifactdir along
with the citool-debug.log
ensure that the ansible.log reported in the results contains the
actual ansible output
You can see what the results look like here:
https://fedorapeople.org/groups/linuxsystemroles/logs/linux-system-roles-ci-testing-pull-linux-system-roles_ci-testing-2-4e69974-centos-8-20200917-202812/artifacts/test.log.html
> hide citool output - ensure ansible.log is correct

- ansible/openshift-playbook.yml
Synchronizes centos7 deployments with the standard deployments. But keep the default for centos7 production as 1 to avoid a thundering herd of production pods when the variable is unset (default for standard production is 8).
> Use deploy_replicas* also for centos7 deployments

- Dockerfile
- Dockerfile.centos7
- test/compose2image.py
- test/run-tests
Can be used to support images whose URL is changing dynamically, like latest Fedora cloud images.
Introduces a new option "compose" in the image dictionary, which can be used instead of "source" and contains the compose URL.
Optionally it can be qualified by "variant" when the compose contains images of multiple variants and specifying only compose would be ambiguous.
Also properly report error when image can't be downloaded as an error not test failure.
Closes #15
> Derive image URL from compose URL

- test/run-tests
If `test_collections` is set to true in the config file (`config.json`) - [0], `lsr_role2collection.py` is downloaded and the role of being tested is converted to the collection format. The role's tests directory is placed outside of the collection and the tests playbooks are executed from there.
[0] default to false.
This PR depends upon these 2 PRs to fix lsr_role2collection.py.
https://github.com/linux-system-roles/auto-maintenance/pull/27
https://github.com/linux-system-roles/auto-maintenance/pull/28
QUESTION: I have tested only with KVM_BACKEND. Could someone tell me how to test locally with CITOOL_BACKEND?
> RHELPLAN-42929 - Collections - script - add CI testing for collection

- test/run-tests
Image URLs are changing now, and the image file has been kept in the cache under a name derived from the URL. This has led to obsolete images images piling up in the cache as the URL has kept changing.
Fix by saving the image file under a filename derived from the image label (like 'fedora-32'), not from the URL. This way there can be only one image in the cache for the given URL.
To determine if the cached file is up to date record its URL in an extended attribute. If the recorded URL does not match the current URL, the image is obsolete and will be redownloaded.
Fixes a problem introduced in #110.
> Keep only latest image file in the cache

- ansible/openshift-playbook.yml
openshift-playbook.yml - Adding "| combine(test_harness_deploy_env_centos7)"
to __test_harness_deploy_env for staging and production centos7 to override
TEST_HARNESS_COLLECTIONS with false.
Note: This PR depends on https://gitlab.cee.redhat.com/rhel-system-roles/test-harness-config/-/merge_requests/73
> RHELPLAN-59406 - Disable the collection tests for centos-7 in deploymentconfig

- Dockerfile
https://github.com/linux-system-roles/test-harness/issues/124
CI tests with collections option fail with "__spec__ is None" if the
role has module_utils #124
To workaround the collections problem in ansible 2.9, pre-installing
the packages on the control node, which module_utils depend upon.
Packages module_utils depending upon:
1) Certificate
libnftnl nftables firewalld firewalld-filesystem python3-nftables
ipset python3-firewall ipset-libs iptables
2) Network
NetworkManager python3-gobject-base wpa_supplicant
3) Storage
none
The details about the ansible 2.9 problem are found in
https://github.com/ansible/ansible/issues/68361
> RHELPLAN-60810 - Fixing a collection CI test failure - "__spec__ is None" if the role has module_utils

- Dockerfile
Reverting the change to preinstall packages for network and certificate roles.
This workaround is no longer needed once https://github.com/linux-system-roles/network/pull/330 and https://github.com/linux-system-roles/certificate/pull/71 are merged.
This reverts commit f3a9a3979bada386ed007c4920fd152426ba96d0.
> Revert "RHELPLAN-60810 - Fixing a collection CI test failure - "__spec__ is None" if the role has module_utils"

- test/run-tests
Clone the PR repo under a path that has the FQRN `org.role/` e.g.
`linux-system-roles.storage/`
Get rid of any tests/roles/ dirs/symlinks (except `caller/`).
Set the `ANSIBLE_ROLES_PATH` environment variable to point to
the directory containing the FQDN directory.
> Use ANSIBLE_ROLES_PATH; remove tests/roles/ dirs/symlinks

- test/run-tests
It attempts to add functionality to get the latest image from a URL, where URL (`source` field in the config) is a alias for the latest image.
It is useful for CentOS images.
It uses the metadata of the web resource to distinguish whether a new image needs to be downloaded.
> runtest: Add support for alias image URLs

- test/run-tests
Use the `getheader` method instead of accessing `headers` directly.
The `getheader` method will do a case-insensitive lookup of the
requested header.
This solves the following problem:
```
Traceback (most recent call last):
File "/test/run-tests", line 1035, in handle_task
result = task.run(
File "/test/run-tests", line 476, in run
image_path = fetch_image(image_url, cachedir, self.image["name"])
File "/test/run-tests", line 297, in fetch_image
image_last_modified_by_src = get_metadata_from_url(url, "Last-Modified")
File "/test/run-tests", line 276, in get_metadata_from_url
return dict(url_response.getheaders())[metadata_key]
KeyError: 'Last-Modified'
```
The problem is that the server is returning the header as all lower case
`last-modified`.  This must have changed recently.
> use the getheader method rather than headers directly

- test/run-tests
We currently support image formats like: `rhel-8` and `rhel-x`.
This PR adds support for the format "rhel-8-y". The `-y` part is ignored.
> runtest: Add support for image names with two hyphens (rhel-8-y)

- test/run-tests
Revert "Use ANSIBLE_ROLES_PATH; remove tests/roles/ dirs/symlinks"
This reverts commit 6a3b1a97ec86526172778bc6f705daf31d2ea92a.
Revert "remove the parent_dir"
This reverts commit f772998bc4f86809706cc6bd46a8c44386334fcf.
> Revert Use ANSIBLE_ROLES_PATH; remove tests/roles/ dirs/symlinks

- test/run-tests
Do not reuse the directories used for converting the role and
tests to collection format.  Instead, for each set of test
playbooks, create new temporary directories for the role and
tests, and remove them when finished.
> make a new tempdir for collections, tests for each iteration

- test/run-tests
Before running the tests, install tests requirements specified in `requirements.yml` file (if exists) by `ansible-galaxy`. Requirements are installed under the `tests/roles` directory.
> [RFE] Install tests requirements

- Dockerfile.centos7
Use python3.6 version of packages
> Use the same qcow2 inventory/VM provision script in centos7 as in Fedora

- Dockerfile.centos7
netaddr and jmespath are for python2 for ansible, not for python3
for the standard test script
> netaddr and jmespath are for python2 for ansible

- test/run-tests
due to the recent commit https://github.com/linux-system-roles/auto-maintenance/pull/83
we need to add the runtime.yml file for lsr_role2collection to use
> the file meta/runtime.yml is now needed for collections

- Dockerfile.centos7
Bug 1989197 - drop support for Ansible 2.8
https://bugzilla.redhat.com/show_bug.cgi?id=1989197
> Drop Ansible 2.8 from EL7 and install ansible 2.9 instead

- Dockerfile.a212
- Dockerfile.centos7
- README.md
- ansible/openshift-playbook.yml
- test/run-tests
Add support for ansible 2.12 using the ansible 2.12 container image
from quay.io.  Will need to update once they move it to stable.
Allow image config to specify env. vars. for each image.  This should
fix some problems we have seen on el6 and el7.
Allow to specify Ansible skip tags. For example, qemu CI can skip the
cleanup section.  The new 2.12 runner needs to skip nvme since it isn't
supported on the container image platform.
Always grab the standard-inventory-qcow2 script from pagure since the
package is released very infrequently and we need all of the newly
merged functionality.
Add support for github paging when retrieving a list of items from
github.
Add reporting of the github rate limit information.
Add support for being able to test a role without a PR by using PR
number `0`. …
> support ansible 2.12; support skip tags; support env. vars. in config

- Dockerfile.centos7
- test/run-tests
Use the centos7 image from quay.io which is up-to-date
Add the ability to skip problematic images with `TEST_HARNESS_SKIP_IMAGES`
This allows us to skip fedora and rhel-x when using the
centos7 controller, which crash when using qemu.
> use quay.io for centos7; skip problematic images

- test/run-tests
Add support for TEST_HARNESS_ONLY_TESTS - if you specify this,
run-tests will only run tests matching these space delimited
patterns e.g.
```
TEST_HARNESS_ONLY_TESTS="tests_some_test.yml tests_other_test.yml"
```
> add support for TEST_HARNESS_ONLY_TESTS

- test/run-tests
Since we are tight on disk space for /cache, remove the .snap and
yum cache files by default after the PR test run.
Added parameter `--keep-snap-cache` in case the user wants
to keep the cache files.
> Remove snapshot, yum caches by default

- test/run-tests
This relies on https://github.com/linux-system-roles/tox-lsr/pull/83 to
fix the test reporting.
Instead of creating a single, monolithic ansible.log for all tests,
create a separate ansible log file for each test playbook, named
TESTS_PLAYBOOK.yml.log.  The resulting test.log.html has links to
each test log file.  If doing collections, the ansible log file will have
the results of both the legacy role test and the collection format
test.
Get rid of the citool stuff.  The code was becoming too complex to
manage.
Fix the batch mode log reporting.
> ansible log per test; no citool; fix batch mode reporting
